### ISSUE TITLE
[v0.26.0] show graph command fails

### ISSUE THREAD

**Issue by codebuff** [foambubble/foam#1400]
### Describe the bug

Show graph command fails.  I am using this inside [code-server](https://github.com/coder/code-server) , please see logs below

```
2024-10-02 15:57:59.507 [error] TypeError: fetch failed
	at node:internal/deps/undici/undici:12502:13
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async LH (/home/vscode/.local/share/code-server/extensions/foam.foam-vscode-0.26.0/out/bundles/extension-node.js:275:6895)
	at async IH (/home/vscode/.local/share/code-server/extensions/foam.foam-vscode-0.26.0/out/bundles/extension-node.js:275:6190)
	at async /home/vscode/.local/share/code-server/extensions/foam.foam-vscode-0.26.0/out/bundles/extension-node.js:275:4825
	at async u.h (/usr/lib/code-server/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:161:210546) foam-vscode.show-graph {"value":"foam.foam-vscode","_lower":"foam.foam-vscode"}
```

### Steps to Reproduce the Bug or Issue

Try Foam:show graph command

### Expected behavior

Graph appears

### Operating System Version

inside code-server instance, client is browser on Mac OS

### Visual Studio Code Version

1.93.1

### Additional context

As a workaround, I am reverting back to 0.25.12

**Comment by mescanne** [comment]
This also fails on vscode serve-web. There is also a warning the console:
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.

I don't think that warning is connected... there are no other errors or warnings in the network or console.

**Comment by mihaimaruseac** [comment]
This also happened to me on Linux with either vscode or codium options.

**Comment by sbussard-inversemetric** [comment]
same. bump

**Comment by riccardoferretti** [comment]
@pderaaij is looking into the issue.
In the meantime, as 0.26 didn't introduce anything new except for the support of Foam as web extension, I recommend the workaround shared above about reverting to 0.25.12

**Comment by VerveLight** [comment]
Confirming that rolling back to 0.25.12 gets this working in the github codespace/web docker. 

With 0.26.4 failing.

**Comment by VerveLight** [comment]
A tiny bit ironic if 0.26 enables it as a web Ide extension, as i'm unable to get foam commands to work on gitlab's web ide, and on github web ide, when clicking on a path it gives a windows path and doesnt refer to the correct root / path but the graph is atleast visible.  So swapped to the code spaces version for this purpose, of which as mentioned above, the rollback is required to be able to open.

**Comment by riccardoferretti** [comment]
Can you please verify this is still happening, and in that case include steps to reproduce it?

**Comment by sbussard-inversemetric** [comment]
Open a repo/folder in a running code-server instance and run `Foam: Show Graph`

<img width="515" height="191" alt="Image" src="https://github.com/user-attachments/assets/e011df52-5be8-4f19-83d8-f5ce88b2615c" />

**Comment by ghost** [comment]
Hello,
I have the same issue. I first install foam, everything is ok. I close VSCodium an re-open a .md file and then none of the foam extension commands are working (i had the same problem on a linux or a windows version today)

<img width="444" height="153" alt="Image" src="https://github.com/user-attachments/assets/9976a4b9-5fc2-4621-83cd-18ba64ed8256" />
