### ISSUE TITLE
Seems like wiki-links broke with the latest VSCode update

### ISSUE THREAD

**Issue by zomars** [foambubble/foam#278]
Is there a way of troubleshooting this? Currently I cannot click on wiki-links nor create new notes from wiki-links.

![Captura de Pantalla 2020-10-06 a la(s) 7 48 01](https://user-images.githubusercontent.com/3504472/95210103-5d879980-07a8-11eb-8d67-d8d667b5ea22.png)

**Comment by riccardoferretti** [comment]
mmmm.. I just tested with the latest VSCode and things seem to work fine for me.

can you check you have the Markdown Notes extensions installed and enabled?

**Comment by zomars** [comment]
Hi thanks for the response @riccardoferretti. Yes I have the extension installed I'm following their troubleshooting guide and see what I can find.

On a side note I'm getting this warning also:

![image](https://user-images.githubusercontent.com/3504472/95215444-33d17100-07ae-11eb-8f2d-c0acccdcc371.png)

**Comment by zomars** [comment]
Checking on the Extension Host Log:

```
[2020-10-06 08:41:23.636] [exthost] [error] [kortina.vscode-markdown-notes] provider FAILED
[2020-10-06 08:41:23.636] [exthost] [error] Error: command failed with error code 2: error parsing glob '!/{**/node_modules,**/bower_components,**/*.code-search,**/.git,**/.next,**/public/{[^i],?[^n]}*,**/dist,**/_ide_helper.php,**/composer.lock,**/package-lock.json,storage,.phpunit.result.cache,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store}': nested alternate groups are not allowed

    at Object.t.deserializeSearchError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5263:575)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5343:12
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5341:145
[2020-10-06 08:41:23.736] [exthost] [error] [kortina.vscode-markdown-notes] provider FAILED
[2020-10-06 08:41:23.736] [exthost] [error] Error: command failed with error code 2: error parsing glob '!/{**/node_modules,**/bower_components,**/*.code-search,**/.git,**/.next,**/public/{[^i],?[^n]}*,**/dist,**/_ide_helper.php,**/composer.lock,**/package-lock.json,storage,.phpunit.result.cache,**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store}': nested alternate groups are not allowed
```

Seems to be some deprecated regex on my `"search.exclude"` settings, I've removed the entries with regex and now it's working again.

**Comment by riccardoferretti** [comment]
Glad it's working! will close the issue
