### ISSUE TITLE
Error running `yarn watch` in foam-core

### ISSUE THREAD

**Issue by bronson** [foambubble/foam#673]
- Foam version: v0.13.7
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: N/A

**Summary**

foam-core's README suggests running `yarn watch`: https://github.com/foambubble/foam/tree/master/packages/foam-core#yarn-watch

But running `yarn watch` on my system produces an error:

<details>
<summary>`Error: Incompatible tsconfig option. Module resolves to 'CommonJS'. This is incompatible with rollup, please use 'module: "ES2015"' or 'module: "ESNext"'`</summary>

```
✖ Failed to compile
Error: Incompatible tsconfig option. Module resolves to 'CommonJS'. This is incompatible with rollup, please use 'module: "ES2015"' or 'module: "ESNext"'.

    at checkTsConfig (/Users/bronson/foam/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25059:15)
    at parseTsConfig (/Users/bronson/foam/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25090:5)
    at Object.options (/Users/bronson/foam/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:28951:73)
    at applyOptionHook (/Users/bronson/foam/node_modules/rollup/dist/shared/node-entry.js:13788:31)
    at Array.reduce (<anonymous>)
    at getInputOptions$1 (/Users/bronson/foam/node_modules/rollup/dist/shared/node-entry.js:13810:41)
    at /Users/bronson/foam/node_modules/rollup/dist/shared/node-entry.js:13878:30
    at Generator.next (<anonymous>)
    at /Users/bronson/foam/node_modules/rollup/dist/shared/node-entry.js:50:71
    at new Promise (<anonymous>)
```

</details>

**Additional information**

Noticed https://github.com/foambubble/foam/pull/193 talks about removing the need to run the watcher. Maybe watching is obsolete and the fix is as simple as updating the README?

**Comment by riccardoferretti** [comment]
fixed some time ago
