### ISSUE TITLE
Certain wikilink names like [[constructor]] break foam

### ISSUE THREAD

**Issue by vojavocni** [foambubble/foam#705]
- Foam version: 0.13.8
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Adding a placeholder wiki-link with a special name like [[constructor]], which is a reserved keyword in javascript, breaks foam with an error:
```
An error occurred while bootstrapping Foam. TypeError: this.backlinks[target.path].push is not a function at FoamGraph.connect
``` 

Full traceback (on my computer):

```
An error occurred while bootstrapping Foam. TypeError: this.backlinks[target.path].push is not a function at FoamGraph.connect (/home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:2941:33) at /home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:3000:14 at Array.forEach (<anonymous>) at FoamGraph.resolveResource (/home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:2997:20) at /home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:2845:20 at Array.forEach (<anonymous>) at Function.fromWorkspace (/home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:2844:37) at /home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:3663:29
```

**Steps to reproduce**
1. Simply add the placeholder [[constructor]] into any note  
2. Reload vscode

**Additional information**
The same error might happen on other similar keywords, but I cannot confirm it at the moment. This was discovered by accident, and is probably a very special edge case.

**Comment by vojavocni** [comment]
I have confirmed the same for other `Object.prototype` methods  `toString` and `valueOf`. These are not likely to be placeholders in foam, but it seems there is a pattern here and that `Object.prototype` method names break foam when used as wiki-link names.
