### ISSUE TITLE
Foam crashes on load - cannot execute any commands

### ISSUE THREAD

**Issue by wolverdude** [foambubble/foam#908]
- Foam version: v0.17.2
- Platform: Mac
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: N/A

**Summary**
I cannot execute any Foam commands. It crashes immediately with a popup message like this:

```
Command 'Foam: Open Daily Note' resulted in an error (command 'foam-vscode.open-daily-note' not found)
```

**Steps to reproduce**
1. Install the extension
2. Execute any Foam command from the command palette.

**Additional information**

VsCode Version: 1.63.2 (Universal)

This isn't a widespread issue from what I can tell. I came across it when I first tried to install a month ago, and it still persists. I couldn't find anyone else with the same problem.

I've tried reinstalling Foam, quitting and reopening VsCode, and restarting my machine. I even upgraded the OS and nothing has changed. I haven't tried reinstalling VsCode yet.

There is no Foam log because it crashes on initalization, but the Extension Host log shows this stacktrace:

```
[2022-01-12 11:02:06.281] [exthost] [error] Activating extension foam.foam-vscode failed due to an error:
[2022-01-12 11:02:06.281] [exthost] [error] TypeError: Cannot read property '0' of undefined
	at Object.<anonymous> (/Users/me/.vscode/extensions/foam.foam-vscode-0.17.2/out/services/templates.js:17:86)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1316)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32222)
	at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28887)
	at Function.f._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:61699)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/me/.vscode/extensions/foam.foam-vscode-0.17.2/out/dated-notes.js:13:21)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1316)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32222)
	at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28887)
	at Function.f._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:61699)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/me/.vscode/extensions/foam.foam-vscode-0.17.2/out/features/open-daily-note.js:4:23)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1316)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32222)
	at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28887)
	at Function.f._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:61699)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/me/.vscode/extensions/foam.foam-vscode-0.17.2/out/features/index.js:8:43)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1316)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32222)
	at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28887)
	at Function.f._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:61699)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/me/.vscode/extensions/foam.foam-vscode-0.17.2/out/extension.js:9:20)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1316)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:32222)
	at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:28887)
	at Function.f._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:61699)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at v._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:30297)
	at v._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:12958)
	at v._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:100:11931)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

**Comment by mlwarner** [comment]
Can reproduce it on my end. Stack trace points toward the template file.

https://github.com/foambubble/foam/blob/17cb61948047d53227ebd9eebd1c16472f7c5400/packages/foam-vscode/src/services/templates.ts#L20-L22

Looks like Foam doesn't know where to open the daily note since you don't have a workspace open! Just open up a folder in vscode and you should be able to run that command.

We could probably make this a bit nicer, depending on what features we want to support.

1. Add support for opening daily notes without a workspace (can we do this? temporary file?)
2. Or, just provide a more useful error message when this happens. Suggest the user open a workspace.

**Comment by mlwarner** [comment]
For (2) we can update the commands to only show when a user has a workspace. The current commands don't have any `when` clauses to restrict when they are available

https://github.com/foambubble/foam/blob/17cb61948047d53227ebd9eebd1c16472f7c5400/packages/foam-vscode/package.json#L146-L168

https://code.visualstudio.com/api/extension-guides/command#creating-new-commands

https://code.visualstudio.com/api/references/when-clause-contexts

The `workbenchState` and `workspaceFolderCount` both seem like they would work. Could probably restrict daily note to `workspaceFolderCount >= 1`

**Comment by wolverdude** [comment]
Ah, I see. Yes, this does seem to be the issue. Restricting would probably be useful, though that wouldn't have solved my problem ultimately. Had I installed it and seen no commands available, I still would've been perplexed.

I suppose a very hacky way to handle this would be to create a command that only shows when a workspace isn't open whose title is something to the effect of `Foam: You must open a workspace to use commands.`
