### ISSUE TITLE
Got Error at bootstrapping in V0.18.0

### ISSUE THREAD

**Issue by Lauviah0622** [foambubble/foam#974]
### Describe the bug

I got some problem in Foam v0.18.0.  and here's the error message. 

```
[[object Object]]Cannot read properties of undefined (reading 'split')
```

```
TypeError: Cannot read properties of undefined (reading 'split')
    at FoamWorkspace.find (vscode-file://vscode-app/Users/feversocial/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/workspace.js:105:44)
    at MarkdownResourceProvider.resolveLink (vscode-file://vscode-app/Users/feversocial/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/services/markdown-provider.js:97:53)
    at FoamWorkspace.resolveLink (vscode-file://vscode-app/Users/feversocial/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/workspace.js:130:33)
    at FoamGraph.update (vscode-file://vscode-app/Users/feversocial/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/graph.js:84:50)
    at Function.fromWorkspace (vscode-file://vscode-app/Users/feversocial/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/graph.js:68:15)
    at Object.exports.bootstrap (vscode-file://vscode-app/Users/feversocial/.vscode/extensions/foam.foam-vscode-0.18.0/out/core/model/foam.js:16:37)
```

I guess the cause of the problem could be this file but I didn't go deeper.
```
packages/foam-vscode/src/core/model/workspace.ts
```

There is work in prev Foam version v0.17.8

### Small Reproducible Example

https://github.com/Lauviah0622/Foam-v0.18.0-issue-reproduce

I split out the cause folder of my note directory, Bootstrapping of Foam cause error at repo. 

### Steps to Reproduce the Bug or Issue

1. update foam to v0.18.0. 
2. the error come from foam bootstrap process 

### Expected behavior

As a user, I expect the Foam execute successfully. But I got the error message

### Operating System Version

Darwin x64 20.6.0

### Visual Studio Code Version

 1.66.0 (Universal)

### Additional context

whole version info 
```
Version: 1.66.0 (Universal)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z (1 wk ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 20.6.0
```

**Comment by femto-code** [comment]
Same issue here - even after updating to v0.18.1.

I did not have any problems before - VS Codium now reports 13 uncaught errors
`Cannot read properties of undefined (reading 'split')`

**Comment by kenimou** [comment]
Same, the last working version is 0.17.8

**Comment by femto-code** [comment]
@riccardoferretti I can confirm that! The error in my case was caused by a single file which made use of a wikilink to a section of the same file.
Removing the link fixed it immediately.
